export const DOT = "dot";
export const NICKNAME = "nickname";
export const HEART = "heart";
export const CONSTELLATION_STAR = "constellation_star";
export const HOME = "home";
export const GENERIC = "generic";
export const GAS = "gas";
export const PARKING = "parking";
export const CAR_RENTAL = "car_rental";
export const LODGING = "lodging";
export const RESORT = "resort";
export const BANK_EURO = "bank_euro";
export const BANK_DOLLAR = "bank_dollar";
export const BANK_JP = "bank_jp";
export const ATM = "atm";
export const BANK_INTL = "bank_intl";
export const HOSPITAL_H = "hospital_H";
export const HOSPITAL_SHIELD = "hospital_shield";
export const PHARMACY = "pharmacy";
export const FIRE_JP = "fire_jp";
export const MEDICAL = "medical";
export const TREE = "tree";
export const MOUNTAIN = "mountain";
export const STADIUM = "stadium";
export const PAW = "paw";
export const CAMPING = "camping";
export const CEMETERY = "cemetery";
export const GOLF = "golf";
export const FLOWER = "flower";
export const HIKING = "hiking";
export const BOATING = "boating";
export const FISHING = "fishing";
export const HOTSPRING = "hotspring";
export const AIRPORT = "airport";
export const RESTAURANT = "restaurant";
export const BAR = "bar";
export const CAFE = "cafe";
export const GLASS = "glass";
export const SHOPPINGBAG = "shoppingbag";
export const SHOPPINGCART = "shoppingcart";
export const PALETTE = "palette";
export const LIGHTHOUSE = "lighthouse";
export const THEATER = "theater";
export const CAMERA = "camera";
export const DICE = "dice";
export const DOLPHIN = "dolphin";
export const EVENT_VENUE = "event_venue";
export const FERRISWHEEL = "ferriswheel";
export const HISTORIC = "historic";
export const HISTORIC_CN = "historic_cn";
export const MUSEUM = "museum";
export const MOVIE = "movie";
export const MONUMENT = "monument";
export const NOTE = "note";
export const RELIC_JP = "relic_jp";
export const CIVIC_BLDG = "civic_bldg";
export const POSTOFFICE = "postoffice";
export const POSTOFFICE_JP = "postoffice_jp";
export const LIBRARY = "library";
export const POLICE = "police";
export const POLICE_JP = "police_jp";
export const SCHOOL = "school";
export const SCHOOL_CN_JP = "school_cn_jp";
export const BRIDGE = "bridge";
export const RESTROOM = "restroom";
export const CITY_OFFICE_JP = "city_office_jp";
export const CIVIL_OFFICE_JP = "civil_office_jp";
export const GOVERNMENT_CN = "government_cn";
export const WORSHIP_TEMPLE = "worship_temple";
export const WORSHIP_JEWISH = "worship_jewish";
export const WORSHIP_MORMON = "worship_mormon";
export const WORSHIP_DHARMA = "worship_dharma";
export const WORSHIP_BUDDHIST = "worship_buddhist";
export const WORSHIP_HINDU = "worship_hindu";
export const WORSHIP_JAIN = "worship_jain";
export const WORSHIP_SHINTO = "worship_shinto";
export const WORSHIP_SIKH = "worship_sikh";
export const WORSHIP_ISLAM = "worship_islam";

export const families = {
  services: { color: "909ce1" },
  health: { color: "f88181" },
  outdoor: { color: "4db546" },
  transport: { color: "10bdff" },
  food: { color: "ff9e67" },
  shopping: { color: "4b96f3" },
  entertainment: { color: "13b5c7" },
  civil: { color: "7b9eb0" },
  worship: { color: "7b9eb0" }
};

export const icons = {
  dot: { color: "7b9eb0" },
  nickname: { color: "4285f4" },
  heart: { color: "fa507d" },
  constellation_star: { color: "fbc02d" },
  home: { color: "4285f4" },
  generic: { color: "acc1" },
  gas: { family: "services" },
  parking: { family: "services" },
  car_rental: { family: "services" },
  lodging: { family: "services" },
  resort: { family: "services" },
  bank_euro: { family: "services" },
  bank_dollar: { family: "services" },
  bank_jp: { family: "services" },
  atm: { family: "services" },
  bank_intl: { family: "services" },
  hospital_H: { family: "health" },
  hospital_shield: { family: "health" },
  pharmacy: { family: "health" },
  fire_jp: { family: "health" },
  medical: { family: "health" },
  tree: { family: "outdoor" },
  mountain: { family: "outdoor" },
  stadium: { family: "outdoor" },
  paw: { family: "outdoor" },
  camping: { family: "outdoor" },
  cemetery: { family: "outdoor" },
  golf: { family: "outdoor" },
  flower: { family: "outdoor" },
  hiking: { family: "outdoor" },
  boating: { family: "outdoor" },
  fishing: { family: "outdoor" },
  hotspring: { family: "outdoor" },
  airport: { family: "transport" },
  restaurant: { family: "food" },
  bar: { family: "food" },
  cafe: { family: "food" },
  glass: { family: "food" },
  shoppingbag: { family: "shopping" },
  shoppingcart: { family: "shopping" },
  palette: { family: "entertainment" },
  lighthouse: { family: "entertainment" },
  theater: { family: "entertainment" },
  camera: { family: "entertainment" },
  dice: { family: "entertainment" },
  dolphin: { family: "entertainment" },
  event_venue: { family: "entertainment" },
  ferriswheel: { family: "entertainment" },
  historic: { family: "entertainment" },
  historic_cn: { family: "entertainment" },
  museum: { family: "entertainment" },
  movie: { family: "entertainment" },
  monument: { family: "entertainment" },
  note: { family: "entertainment" },
  relic_jp: { family: "entertainment" },
  civic_bldg: { family: "civil" },
  postoffice: { family: "civil" },
  postoffice_jp: { family: "civil" },
  library: { family: "civil" },
  police: { family: "civil" },
  police_jp: { family: "civil" },
  school: { family: "civil" },
  school_cn_jp: { family: "civil" },
  bridge: { family: "civil" },
  restroom: { family: "civil" },
  city_office_jp: { family: "civil" },
  civil_office_jp: { family: "civil" },
  government_cn: { family: "civil" },
  worship_temple: { family: "worship" },
  worship_jewish: { family: "worship" },
  worship_mormon: { family: "worship" },
  worship_dharma: { family: "worship" },
  worship_buddhist: { family: "worship" },
  worship_hindu: { family: "worship" },
  worship_jain: { family: "worship" },
  worship_shinto: { family: "worship" },
  worship_sikh: { family: "worship" },
  worship_islam: { family: "worship" }
};

export default function googleMapIcon(icon, { color, scale } = { scale: 1 }) {
  if (!color) {
    color =
      (icons[icon] &&
        (icons[icon].color || families[icons[icon].family].color)) ||
      "7b9eb0";
  }
  return `https://www.google.com/maps/vt/icon/name=assets/icons/poi/tactile/pinlet_shadow-1-small.png,assets/icons/poi/tactile/pinlet_outline_v2-1-small.png,assets/icons/poi/tactile/pinlet-1-small.png,assets/icons/poi/quantum/pinlet/${icon}_pinlet-1-small.png&highlight=ff000000,ffffff,${color},ffffff?scale=${scale}`;
}
